spring.application.name=Study-buddy

spring.datasource.url=jdbc:postgresql://localhost:5432/studybuddy
spring.datasource.username=postgres
spring.datasource.password=javurina

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect