spring.application.name=Study-buddy

spring.datasource.url=jdbc:postgresql://localhost:5432/studybuddy
spring.datasource.username=postgres
spring.datasource.password=javurina
spring.jpa.hibernate.ddl-auto=create
spring.sql.init.mode=always
spring.jpa.defer-datasource-initialization=true
spring.jpa.show-sql=true
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect